name: UUIDVault
main: ${project.groupId}.plugin.spigot.UUIDVaultSpigotPlugin
version: ${plugin.version}
author: ${plugin.author}
website: ${plugin.url}
description: ${plugin.description}
load: STARTUP